# Generated by Django 3.0.4 on 2020-05-25 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
