# Generated by Django 3.0.4 on 2020-06-01 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
