# Generated by Django 3.0.4 on 2020-06-01 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20200601_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='djangoUser',
        ),
    ]
